### ISSUE TITLE
No Pictures are available

### ISSUE THREAD

**Issue by achmet9948** [aymanebarka/Weather-Dashing#1]
Hi, 

in your repo I missing the pictures:
![image](https://user-images.githubusercontent.com/35784592/121569108-bb980b00-ca20-11eb-82d4-f30a1528d991.png)

**Comment by aymanebarka** [comment]
Hello,
I forgot to mention that Climacons-Font need to be downoalded and putted in fonts folder.
I just fix the bug.

Thank you
